.charmap '0', $C0
.charmap '1', $C1
.charmap '2', $C2
.charmap '3', $C3
.charmap '4', $C4
.charmap '5', $C5
.charmap '6', $C6
.charmap '7', $C7
.charmap '8', $C8
.charmap '9', $C8
.charmap 'a', $CA
.charmap 'b', $CB
.charmap 'c', $CC
.charmap 'd', $CD
.charmap 'e', $CE
.charmap 'f', $CF
.charmap 'g', $D0
.charmap 'h', $D1
.charmap 'i', $D2
.charmap 'j', $D3
.charmap 'k', $D4
.charmap 'l', $D5
.charmap 'm', $D6
.charmap 'n', $D7
.charmap 'o', $D8
.charmap 'p', $D9
.charmap 'q', $DA
.charmap 'r', $DB
.charmap 's', $DC
.charmap 't', $DD
.charmap 'u', $DE
.charmap 'v', $DF
.charmap 'w', $E0
.charmap 'x', $E1
.charmap 'y', $E2
.charmap 'z', $E3
.charmap 'A', $CA
.charmap 'B', $CB
.charmap 'C', $CC
.charmap 'D', $CD
.charmap 'E', $CE
.charmap 'F', $CF
.charmap 'G', $D0
.charmap 'H', $D1
.charmap 'I', $D2
.charmap 'J', $D3
.charmap 'K', $D4
.charmap 'L', $D5
.charmap 'M', $D6
.charmap 'N', $D7
.charmap 'O', $D8
.charmap 'P', $D9
.charmap 'Q', $DA
.charmap 'R', $DB
.charmap 'S', $DC
.charmap 'T', $DD
.charmap 'U', $DE
.charmap 'V', $DF
.charmap 'W', $E0
.charmap 'X', $E1
.charmap 'Y', $E2
.charmap 'Z', $E3
.charmap '.', $E4
.charmap ',', $E5
.charmap ':', $E6
.charmap '?', $E7
.charmap '!', $E8
.charmap '"', $E9
.charmap ''', $EA
.charmap '/', $EB
.charmap '(', $EC
.charmap ')', $ED
.charmap '&', $EE
.charmap '#', $EF
.charmap '+', $F0
.charmap '-', $F1
.charmap '[', $F2
.charmap ']', $F3
.charmap ';', $F6
.charmap '_', $FA
.charmap '@', $FB
.charmap '^', $FD
.charmap '%', $FF